---
- name: Raspberry Pi Setup
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - package1
        - package2
        # Add more packages as needed

    - name: Run custom commands
      shell: |
        # Your custom commands here
        # For example:
        wget -O somefile.tar.gz http://example.com/somefile.tar.gz
        tar -xzvf somefile.tar.gz
        cd somefile
        ./configure
        make
        sudo make install

